### ISSUE TITLE
[Bug] MeSH descriptors out of date & incorrect field name

### ISSUE THREAD

**Issue by EssentiallyNoah** [dpriskorn/OpenAlexAPI#6]
MeSH descriptors are out of date. Have been increased to 10 in length:
[https://www.nlm.nih.gov/pubs/techbull/ma13/ma13_mesh_ui_expand.html](https://www.nlm.nih.gov/pubs/techbull/ma13/ma13_mesh_ui_expand.html)

`is_main_topic` should be `is_major_topic`:
[https://docs.openalex.org/about-the-data/work#mesh](https://docs.openalex.org/about-the-data/work#mesh)

Patched by pull request: #5

**Comment by dpriskorn** [comment]
Fixed in #5
